### ISSUE TITLE
is it possible to play contionous ?

### ISSUE THREAD

**Issue by mesutgungor** [mrcoles/javascript-piano#2]
İs it possiple to play the note as long as the keyboard key pressed or mouse is clicked.

**Comment by mrcoles** [comment]
Unfortunately this won't work, because the code generates discrete sound files and just plays them—which is central to the weird/fun way in which I originally put together this project. You could try hacking around with the code and see if you could loop a sound. A better, more robust alternative might be playing with the browser’s built-in audio APIs, but that’s a whole other thing and out of the scope of this project.
