### ISSUE TITLE
May be it's easy nowadays to make the app work in iOS?

### ISSUE THREAD

**Issue by davay42** [mrcoles/javascript-piano#5]
I'm very happy to find this code, so I can create an open music learning resource! But it's hard for me to figure out, what are the problems with iOS? May be it's easier now to make it work? I'm sure there are some new convenient libraries and articles about those problems. 
Or you can just point out your ways of thinking in repairing it?

**Comment by mrcoles** [comment]
I think when I wrote this, iOS had strict controls over when you can and cannot play sounds. There may have been some other issues related to timing and concurrency of audio files.

For iOS you may have more luck looking into a native app, or if you want to develop one yourself in JavaScript, you should take a look at what APIs are available for audio, since my project is generating entire audio files in JavaScript as opposed to using an API and the latter approach would be much more efficient.
